apiVersion: 1
datasources:
  - access: proxy
    basicAuth: false
    editable: false
    isDefault: true
    jsonData: 
      implementation: prometheus
      handleGrafanaManagedAlerts: false
    name: alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://192.168.100.243:9090
    version: 1
