version: '3'

services:

  postgres:
    container_name: savannahdb
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ~/apps/savannah/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=savannah
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=savannah
