version: '3'

services:

  postgres:
    container_name: savannahdb
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ~/apps/savannah/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=savannah
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=savannah

  sil-api:
    container_name: sil-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    tty: true
    env_file:
      - .env
    depends_on:
      - postgres
